### ISSUE TITLE
XML doesn't render in Chrome

### ISSUE THREAD

**Issue by mathrick** [hanshuebner/lmman#1]
For whatever reason, Chrome dislikes the presentation in XML (empty page with "xml-stylesheet" as its only node is shown), making it impossible to consume the current lmman. Prerendered HTML for the web would be nice to have.

**Comment by hanshuebner** [comment]
https://github.com/hanshuebner/lmman/commit/84d231832ec1b59a65926ee6aa5cc8c000b3ec96 fixes this issue.  Sorry that it took so long.
