### ISSUE TITLE
missing method names

### ISSUE THREAD

**Issue by Devon7** [hanshuebner/lmman#3]
E.g., from the original text

	Method: pathname :host
	Method: pathname :device
	Method: pathname :directory
	Method: pathname :name
	Method: pathname :type
	Method: pathname :version

	These return the components …

method names are missing in Mozilla Firefox 102.7.0esr

	25.2 Pathname Components
	⋮
	Method	pathname
	Method	pathname
	Method	pathname
	Method	pathname
	Method	pathname
	Method	pathname

	These return the components …

**Comment by hanshuebner** [comment]
I think this is fixed, I'd appreciate your review and confirmation.

**Comment by Devon7** [comment]
The original 1984 Sixth Edition Orangual page 550 text reads

**24.2.2 Pathname Component Operations**

**:host**         		 _Operation on_ **pathname**
**:device**       		 _Operation on_ **pathname**
**:directory**    		 _Operation on_ **pathname**
**:name**         		 _Operation on_ **pathname**
**:type**         		 _Operation on_ **pathname**
**:version**      		 _Operation on_ **pathname**

with left justified :keyword method names and right justified "Operation on pathname"
but Mozilla Firefox 102.7.0esr shows https://HansHuebner.github.io/lmman/pathnm.xml#directory%20(pathname) as

25.2 Pathname Components
⋮
**pathname-host-method**     	 _Method_
**pathname-device-method**   	 _Method_
**pathname-directory-method**	 _Method_
**pathname-name-method**     	 _Method_
**pathname-type-method**     	 _Method_
**pathname-version-method**  	 _Method_

with left justified XML names and right justified "Method" - not correct.

**Comment by hanshuebner** [comment]
I made another change that should more closely resemble what you've lined out.  It would be nicer if the XSLT transformation would render these operations specially, but I'm not currently in the doing that.  A pull request to fix it properly would be gladly accepted though.

**Comment by Devon7** [comment]
The original reads
**:host** ♢ _Operation on_ **pathname**

It would be OK to say
**:host** ♢ _Method on_ **pathname**

or a little confusing to say
**:host** ♢ _Method_

or more confusing to say
**:host** _Operation on pathname_ ♢ _Method_

or most confusing to say
**:host Operation on pathname** ♢ _Method_
which is what it says now, but at least the method name is present, which is the essential.

♢ indicates maximum whitespace separating left-justified from right-justified text.

**Comment by hanshuebner** [comment]
Hi Devon,

I think it looks better now, after I have applied a more systematic fix to
the XML files and corrected the rendering:

[image: image.png]

Meta-methods are still not displayed correctly, though.  Can you have a
look at the streams chapter (which defines a lot of metamethods) and tell
me how those should look like?  I suspect it would be similar to methods,
but does it say "meta-operation"?

Here's the current, wrong rendition:

[image: image.png]

Thank you,
Hans

**Comment by Devon7** [comment]
*SIGH* Taking the plunge deeper into yak-shaving until the next paying customer comes along!
Orangual page 461 reads
**22.3.2 Standard Input Stream Operations**

**:tyi** &optional _eof_ ☆ _Operation on streams_
      The stream inputs one character ☆☆☆ the **:tyi** operation does not echo

Firefox sees
**stream** &optional _eof_ ☆ _Meta-Method_
      The stream inputs one character ☆☆☆ the **:tyi** operation does not echo

omitting the section header and operation/"method" names therein.

☆ indicates horizontal whitespace separating left-justified from right-justified text.
☆☆☆ indicates elided text in the same paragraph.

**Comment by Devon7** [comment]
This issue is incorrectly marked closed - method names are still missing, as shown above.
