### ISSUE TITLE
Section 5.12 improperly changed to a separate chapter

### ISSUE THREAD

**Issue by Devon7** [hanshuebner/lmman#4]
If this were an intentional editorial change, it would be necessary to increment the edition number, update the edition date, add another author, and rewrite the first paragraph of chapter 5.

**Comment by hanshuebner** [comment]
The change is described in [the preface for the HTML version](https://hanshuebner.github.io/lmman/ht-preface.xml) which I feel is sufficient.

**Comment by hanshuebner** [comment]
I have made a small editorial change to the intro of chapter 5 to remove the mentioning of resources.

The reason why I made "Resources" into a separate chapter is that I found it to be important enough to not be buried in a place where it would be hard to find.  I'm not that certain that it was a great choice, but that is how things are at this point.  If you want to renumber the chapters and revert the change, feel free to send a PR.

**Comment by Devon7** [comment]
How did I miss the preface to the HTML edition?  What a great place to describe important and unusual aspects of the LispM system, e.g., cdr-coding, resources, the seamless continuum from user to hardware, what else?  Oh, introduce peculiar terminology and the Concept Index.  This way the original chapter numbers can be restored, eliminating that source of confusion.

**Comment by hanshuebner** [comment]
Feel free to contribute some improvements that you deem worthwhile.
